spring:
  data:
    mongodb:
      uri: mongodb+srv://beatrizcompasso203:Bc33441514%40@cluster0.1kk6q.mongodb.net/nextEpisode_database?retryWrites=true&w=majority
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration